# Generated by Django 5.2.3 on 2025-06-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocation',
            name='place_type',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
