# Generated by Django 5.2.3 on 2025-06-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_userlocation_place_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlocation',
            name='place_type',
            field=models.CharField(max_length=100),
        ),
    ]
