# Generated by Django 5.2.3 on 2025-07-10 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_userlocation_place_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlocation',
            name='place_type',
        ),
    ]
